# @package _global_
model:

  sampler:
    name: ParametrizedBernoulliSampler
    trainable: True
    kwargs:
      n_adjs: 32
      gradient_estimator: 'sf'
      initial_theta: 0.05

  gnn:
    name: 'GCN'
    output_noise: 0.0
    out_noise_type: 'gaussian'
    trainable: True
    kwargs: 
      in_channels: 4
      out_channels: 1
      hidden_channels: 2
      num_layers: 1
      add_self_loops: False
      normalize: False
      bias: False

      
    