# @package _global_
dataset:
  name: SGPVAR
  params:
    num_communities: 2
    n_data: 30000
    n_input_features: 4
    input_noise: 1.
    output_noise: 0.
    out_noise_type: 'gaussian'
    sample_probability: 0.75
    seed: 0
    verbose: True
    save_model_params: True
    GNN_name: 'GCN'
    GNN_kwargs:
      in_channels: 4
      out_channels: 1
      hidden_channels: 2
      num_layers: 1
      add_self_loops: False
      normalize: False
      bias: False
